# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "01660e1e156a13fafba99f4848fff302"
name = "Vakaufa"
handle = "vakaufa"
application_url = "https://presentations-reproduce-retro-sic.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "assistor.myshopify.com"
include_config_on_deploy = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,read_products,write_metaobjects"

[auth]
redirect_urls = [
  "https://presentations-reproduce-retro-sic.trycloudflare.com/auth/callback",
  "https://presentations-reproduce-retro-sic.trycloudflare.com/auth/shopify/callback",
  "https://presentations-reproduce-retro-sic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
